name: Build C++ and C# Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest version

      # Set up MSBuild environment (for Visual Studio 2019)
      - name: Set up MSBuild (VS2019)
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '[16,17)'  # VS2019 range (16.x)

      # Set up NuGet (if needed for dependencies)
      - name: Set up NuGet
        uses: NuGet/setup-nuget@v1

      # Restore NuGet packages (important for .NET Framework projects)
      - name: Restore NuGet Packages
        run: nuget restore path/to/solution.sln

      # Verify MSBuild version
      - name: Verify MSBuild installation
        run: msbuild /version

      # Build the C++ project (force x86 for 32-bit compatibility)
      - name: Build C++ Project
        run: msbuild path/to/project.vcxproj /p:Configuration=Release /p:Platform=x86

      # Build the C# project targeting .NET Framework 4.6.1 and 32-bit
      - name: Build C# Project (.NET Framework 4.6.1)
        run: msbuild path/to/solution.sln /p:Configuration=Release /p:Platform="Any CPU" /p:Prefer32Bit=true

      # Upload executables and DLLs as artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Executables
          path: |
            path/to/cpp/project/Release/*.dll
            path/to/csharp/project/bin/Release/*.exe
